### ISSUE TITLE
Templates missing from the template folder

### ISSUE THREAD

**Issue by donovanash** [IterationInsights/Microsoft-Press-Introduction-to-Microsoft-Power-BI-V2#1]
[Microsoft-Press-Introduction-to-Microsoft-Power-BI-V2](https://github.com/IterationInsights/Microsoft-Press-Introduction-to-Microsoft-Power-BI-V2/tree/main)
/Template/

Templates missing for Build Desktop Visualizations: Next Level lesson in Complete Guide to Power BI for Data Analysts by Microsoft Press training on LinkedInLearning

**Comment by dvanwey** [comment]
Templates still missing.

**Comment by donovanash** [comment]
Thank you sir!
